name: "flair_align"
description: write your description here
keywords:
  - flair
  - align
tools:
  - "flair":
      description: "Correction, isoform definition, and alternative splicing analysis of noisy reads (ONT and PacBio)."
      homepage: "https://github.com/BrooksLabUCSC/flair"
      documentation: "https://flair.readthedocs.io/en/latest/"
      tool_dev_url: "https://github.com/BrooksLabUCSC/flair"
      doi: "10.1038/s41467-020-15171-6"
      licence: "['BSD-3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  # 
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - bam:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,bai,sam}"
      
  - psl:
      type: file
      description: Optional with --psl. Aligned reads in psl format can be visualized in IGV or the UCSC Genome browser
      pattern: "*.{psl}"

authors:
  - "@MustafaElshani"
